services:
  - type: web
    name: moodsync-ai-service
    runtime: python3
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: production
    autoDeploy: false
