services:
  - type: web
    name: moodsync-ai-service
    runtime: python3
    plan: free
    buildCommand: |
      echo "Python version check:"
      python --version
      echo "Installing with specific Python 3.10..."
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: false
